### ISSUE TITLE
where can i find datasets?

### ISSUE THREAD

**Issue by karissa** [okfn/dpm#41]
It would be nice to add an example of where datasets could be/where they are and how I could get them. Do I use the path to /dataprotocols.json ?

**Comment by rgrp** [comment]
@karissa great point - the best location for Data Package datasets right now is http://data.okfn.org/data - though we plan to enable ckan instances like datahub.io with "datapackage" support very soon.

**Comment by bnvk** [comment]
@karissa are you thinking you want something programmatic and REST API like to get datapackages?
@rgrp seems like a REST API would be useful, no? Additionally, using the Table of Contents style datapackage itself as we discussed in other threads!

**Comment by rgrp** [comment]
@bnvk there's a *very* crude REST API atm in the form of:

`http://data.okfn.org/data.json`
`http://data.okfn.org/data/path-to/datapackage//datapackage.json`

Obviously with use of CKAN you get something much richer.

**Comment by rgrp** [comment]
FIXED. I'm closing for now. There will likely be work on an improved registry coming soon.

**Comment by bnvk** [comment]
@rgrp actually, you might not want to close that- i'm getting a
JSON error when I pull up the first URL at present....

**Comment by rgrp** [comment]
@bnvk where are you getting an error - which url?

**Comment by bnvk** [comment]
@rgrp the http://data.okfn.org/data.json url shows `There was an error parsing the JSON document. The document may not be well-formed. unterminated string at line 1 column 87218 ` error!
